# Generated by Django 2.2.5 on 2019-09-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='DEFAULT NAME', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='room_d',
            field=models.CharField(default='Something', max_length=500),
        ),
        migrations.AddField(
            model_name='room',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
