# Generated by Django 2.2.5 on 2019-09-25 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20190925_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='title',
        ),
    ]
